/*
 * atmega8.h
 *
 *  Created on: 05 окт. 2015 г.
 *      Author: OmeZ
 */

#ifndef PLATFORM_ATMEGA8_IO_H_
#define PLATFORM_ATMEGA8_IO_H_

#include <avr/io.h>
#include "../../lib/io.h"

// Ports definition
AVR_TOOLKIT_MAKE_PORT(PORTA, DDRA, PINA, PortA, 'A')
AVR_TOOLKIT_MAKE_PORT(PORTB, DDRB, PINB, PortB, 'B')
AVR_TOOLKIT_MAKE_PORT(PORTC, DDRC, PINC, PortC, 'C')
AVR_TOOLKIT_MAKE_PORT(PORTD, DDRD, PIND, PortD, 'D')

// pin configuration
AVR_TOOLKIT_MAKE_PIN(PortA, 0)
AVR_TOOLKIT_MAKE_PIN(PortA, 1)
AVR_TOOLKIT_MAKE_PIN(PortA, 2)
AVR_TOOLKIT_MAKE_PIN(PortA, 3)
AVR_TOOLKIT_MAKE_PIN(PortA, 4)
AVR_TOOLKIT_MAKE_PIN(PortA, 5)
AVR_TOOLKIT_MAKE_PIN(PortA, 6)
AVR_TOOLKIT_MAKE_PIN(PortA, 7)

AVR_TOOLKIT_MAKE_PIN(PortB, 0)
AVR_TOOLKIT_MAKE_PIN(PortB, 1)
AVR_TOOLKIT_MAKE_PIN(PortB, 2)
AVR_TOOLKIT_MAKE_PIN(PortB, 3)
AVR_TOOLKIT_MAKE_PIN(PortB, 4)
AVR_TOOLKIT_MAKE_PIN(PortB, 5)
AVR_TOOLKIT_MAKE_PIN(PortB, 6)
AVR_TOOLKIT_MAKE_PIN(PortB, 7)

AVR_TOOLKIT_MAKE_PIN(PortC, 0)
AVR_TOOLKIT_MAKE_PIN(PortC, 1)
AVR_TOOLKIT_MAKE_PIN(PortC, 2)
AVR_TOOLKIT_MAKE_PIN(PortC, 3)
AVR_TOOLKIT_MAKE_PIN(PortC, 4)
AVR_TOOLKIT_MAKE_PIN(PortC, 5)
AVR_TOOLKIT_MAKE_PIN(PortC, 6)
AVR_TOOLKIT_MAKE_PIN(PortC, 7)

AVR_TOOLKIT_MAKE_PIN(PortD, 0)
AVR_TOOLKIT_MAKE_PIN(PortD, 1)
AVR_TOOLKIT_MAKE_PIN(PortD, 2)
AVR_TOOLKIT_MAKE_PIN(PortD, 3)
AVR_TOOLKIT_MAKE_PIN(PortD, 4)
AVR_TOOLKIT_MAKE_PIN(PortD, 5)
AVR_TOOLKIT_MAKE_PIN(PortD, 6)
AVR_TOOLKIT_MAKE_PIN(PortD, 7)

#endif /* PLATFORM_ATMEGA8_IO_H_ */
